document.writeln("document.writeln(\"<div class=flash-box>");
document.writeln("              <div class=big-pic id=switchbigpic> ");
document.writeln("              <a href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img01.jpg\/\/\"><\/\//a> ");
document.writeln("              <a href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img02.jpg\/\/\"><\/\//a> ");
document.writeln("              <a href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img03.jpg\/\/\"><\/\//a> ");
document.writeln("              <a href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img04.jpg\/\/\"><\/\//a> ");
document.writeln("              <a href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img05.jpg\/\/\"><\/\//a> ");
document.writeln("              <a href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img06.jpg\/\/\"><\/\//a> ");
document.writeln("              <\/\//div>");
document.writeln("              <div class=pic-list_0810>");
document.writeln("                <div id=ul_recom> ");
document.writeln("                <a class=curra id=switchsmapic_0 title=\/\/\"JSB TOUR\/\/\" href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" src=\/\/\"{$t_dir}images\/\//img01s.jpg\/\/\"><span><strong>《三国》壮志未酬身先死asdfasdf<\/\//strong><\/\//span><span>火烧上方谷诸葛亮吐血身亡a65s4df65<\/\//span><\/\//a> ");
document.writeln("                <a id=switchsmapic_1 title=\/\/\"JSB TOUR\/\/\" href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" ");
document.writeln("			  src=\/\/\"{$t_dir}images\/\//img02s.jpg\/\/\"><span><strong>《劳拉现身》性感喜剧片<\/\//strong><\/\//span><span>惹火大美女不爱猛男爱辣妹a4sd4f5as<\/\//span><\/\//a> ");
document.writeln("              <a id=switchsmapic_2 title=\/\/\"JSB TOUR\/\/\" href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" ");
document.writeln("			  src=\/\/\"{$t_dir}images\/\//img03s.jpg\/\/\"><span><strong>《我是业主》聚焦于房事<\/\//strong><\/\//span><span>看二奶情圣对抗物业女经理<\/\//span><\/\//a> ");
document.writeln("              <a id=switchsmapic_3 title=\/\/\"JSB TOUR\/\/\" href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img ");
document.writeln("			  alt=\/\/\"JSB TOUR\/\/\"src=\/\/\"{$t_dir}images\/\//img04s.jpg\/\/\"><span><strong>《大丈夫》勇敢禁忌纯爱<\/\//strong><\/\//span><span>疯狂断背男同爆笑越狱求欢<\/\//span><\/\//a> ");
document.writeln("              <a id=switchsmapic_4 title=\/\/\"JSB TOUR\/\/\" href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\"");
document.writeln("			  src=\/\/\"{$t_dir}images\/\//img05s.jpg\/\/\"><span><strong>为喜欢的球队呐喊助威<\/\//strong><\/\//span><span>vancl世界杯版t恤29元起<\/\//span><\/\//a> ");
document.writeln("              <a id=switchsmapic_5 title=\/\/\"JSB TOUR\/\/\" href=\/\/\"#\/\/\" blockid=\/\/\"2360\/\/\"><img alt=\/\/\"JSB TOUR\/\/\" ");
document.writeln("			  src=\/\/\"{$t_dir}images\/\//img06s.jpg\/\/\"><span><strong>缤纷夏日 多彩匡威<\/\//strong><\/\//span><span>匡威经典常青款7折热卖<\/\//span><\/\//a> ");
document.writeln("              <\/\//div>");
document.writeln("              <\/\//div>");
document.writeln("            <\/\//div>\")");